# Generated by Django 3.2.16 on 2022-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='messsage',
            field=models.CharField(max_length=1000),
        ),
    ]
